### ISSUE TITLE
PhoneTrack'n'LiveTrack

### ISSUE THREAD

**Issue by julien-nc** [jaykijay/harbour-LiveTrack#3]
As i can't find your e-mail :

Hi,

I'm PhoneTrack's developer. I found your app by chance, wandering on the web.

I wonder why you didn't ask me to put references to your app in PhoneTrack's doc/wiki/README/GUI. Would you like me to ?

I'm glad there's a new app to log positions on personal servers. Thanks for LiveTrack.

Unfortunately my phone runs LineageOS. I guess i can't try LiveTrack. Do you have any idea if SailfishOS can be installed in a Virtualbox machine for example ?

If you have any suggestion or criticism about PhoneTrack, i'll be happy to know.

best regards

Julien

**Comment by jaykijay** [comment]
Hi,
just found this again.. i didn't got any Mail for this issue.. very weird..
You can test this app if you install Sailfish-SDK, then you get a virtual Machine which can run this app, but it would be very useless because in this VM you can't spoof a location to get it working.
I used it for a roadtrip in the US with about 9000km of traveling and some days without Network so it had to offline buffer all points and it worked with your Phonetrack App on Nextcloud. Good enough to keep track of everything and keep my Family aware where i am, but there are still some things to do better.. maybe if i find more time for this ;) .. One of my things on todo list is to get it to fetch infos from Phonetrack and manage/select/create Profiles there together with a login to Nextcloud. This would be a dream but is a lot of work for me ;)

If you like you can mention it in your docs :) I would be proud :) One common Store on Sailfish is Openrepos where you can find it, too : https://openrepos.net/content/jayki/livetrack

Thanks for your work providing a really nice Backend !

PS: you can contact me under:  xxxxx
